# -*- coding: utf-8 -*-
"""Cancer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z7kIcLZ_VDjUHSaCU9zvkhU8i-eWh7dP
"""

import pandas as pd 
import numpy as np 
import seaborn as sns
from scipy.stats import norm
import matplotlib.pyplot as plt

"""#Importing Data"""

cancer = pd.read_csv('/content/cancer_classification.csv')

cancer.head(20)

"""#Data Exploration"""

cancer.info()

cancer['benign_0__mal_1'] = cancer['benign_0__mal_1'].astype(str)

sns.scatterplot(x = 'mean radius', y= 'mean symmetry', hue = 'benign_0__mal_1', data = cancer)

"""#Discovering Correlation"""

correl_canc = cancer.corr()
correl_canc

sns.heatmap(cancer.corr(), annot = True)

sns.scatterplot(x = 'mean radius', y= 'mean texture', hue = 'benign_0__mal_1', data = cancer)

sns.scatterplot(x = 'mean radius', y= 'mean area', hue = 'benign_0__mal_1', data = cancer)

sns.scatterplot(x = 'mean radius', y= 'mean perimeter', hue = 'benign_0__mal_1', data = cancer)

sns.scatterplot(x = 'mean radius', y= 'mean smoothness', hue = 'benign_0__mal_1', data = cancer)

sns.scatterplot(x = 'mean radius', y= 'mean compactness', hue = 'benign_0__mal_1', data = cancer)

sns.scatterplot(x = 'mean radius', y= 'mean concavity', hue = 'benign_0__mal_1', data = cancer)

sns.scatterplot(x = 'mean radius', y= 'mean concave points', hue = 'benign_0__mal_1', data = cancer)

sns.scatterplot(x = 'mean radius', y= 'mean symmetry', hue = 'benign_0__mal_1', data = cancer)

sns.scatterplot(x = 'mean radius', y= 'mean fractal dimension', hue = 'benign_0__mal_1', data = cancer)

sns.scatterplot(x = 'mean radius', y= 'radius error', hue = 'benign_0__mal_1', data = cancer)

"""#Discovering Data Raange"""

sns.boxplot(x = 'mean radius', y= 'mean texture', data = cancer)

sns.boxplot(x = 'benign_0__mal_1', y= 'mean radius', data = cancer)

sns.boxplot(x = 'benign_0__mal_1', y= 'mean texture', data = cancer)

